// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using copaHAS.Data;

#nullable disable

namespace copaHAS.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("copaHAS.Models.Estadio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Estadio");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidade = 46000,
                            Cidade = "São Paulo",
                            Nome = "NeoQuímica Arena"
                        },
                        new
                        {
                            Id = 2,
                            Capacidade = 45000,
                            Cidade = "São Paulo",
                            Nome = "Allianz Parque"
                        },
                        new
                        {
                            Id = 3,
                            Capacidade = 75000,
                            Cidade = "Rio de Janeiro",
                            Nome = "Maracanã"
                        },
                        new
                        {
                            Id = 4,
                            Capacidade = 47000,
                            Cidade = "São Paulo",
                            Nome = "Morumbi"
                        },
                        new
                        {
                            Id = 5,
                            Capacidade = 30000,
                            Cidade = "São Paulo",
                            Nome = "Castelão"
                        },
                        new
                        {
                            Id = 6,
                            Capacidade = 20000,
                            Cidade = "São Paulo",
                            Nome = "Brinco de Ouro"
                        },
                        new
                        {
                            Id = 7,
                            Capacidade = 50000,
                            Cidade = "São Paulo",
                            Nome = "Camp Nou"
                        },
                        new
                        {
                            Id = 8,
                            Capacidade = 60000,
                            Cidade = "São Paulo",
                            Nome = "Allianz Arena"
                        },
                        new
                        {
                            Id = 9,
                            Capacidade = 20000,
                            Cidade = "São Paulo",
                            Nome = "Vila Belmiro"
                        },
                        new
                        {
                            Id = 10,
                            Capacidade = 20000,
                            Cidade = "São Paulo",
                            Nome = "Arena Barueri"
                        });
                });

            modelBuilder.Entity("copaHAS.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroCamisa")
                        .HasColumnType("int");

                    b.Property<string>("Posicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SelecaoId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTADIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Tevez",
                            NumeroCamisa = 10,
                            Posicao = "Meio-Campo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Cassio",
                            NumeroCamisa = 12,
                            Posicao = "Goleiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ronaldo",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Fagner",
                            NumeroCamisa = 23,
                            Posicao = "Lateral Direito",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Gil",
                            NumeroCamisa = 4,
                            Posicao = "Zagueiro",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Renato Augusto",
                            NumeroCamisa = 8,
                            Posicao = "Meio-Campo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Paulinho",
                            NumeroCamisa = 15,
                            Posicao = "Meio-Campo",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Yuri Alberto",
                            NumeroCamisa = 9,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Roger Guedes",
                            NumeroCamisa = 10,
                            Posicao = "Atacante",
                            SelecaoId = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Fabio Santos",
                            NumeroCamisa = 6,
                            Posicao = "Lateral Esquerdo",
                            SelecaoId = 0,
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
